### ISSUE TITLE
Incoporate Low Magnification Images in In Vitro Slice Neuron Morphology Reconstruction schema

### ISSUE THREAD

**Issue by jmbudd** [INCF/neuroshapes#359]
In the process of applying Neuroshapes In Vitro Slice Neuron Morphology Reconstruction schema to the curation of combined anatomical and electrophysiolgical slice data from mouse hippocampus, I encountered a number of issues. Since these issues may well arise during the curation of similar datasets for other labs, I thought it might be useful to share them here. I have created a separate ticket for each issue. (This introductory paragraph is repeated in each.)

Low magnification images are often taken to record the position, orientation and size of a labelled neuron (or neurons) relative to cellular boundaries of the tissue slice. These raw data - usually just a single image - are not currently part of the publicly documented Slice schema and yet represents valuable information about its anatomical context of the neuron, e.g. cellular properties can vary according to anatomical axes position especially in hippocampus. 

It is not obvious how low magnification images should be included in the Slice schema. It is not a preview image so does not fit within the FixedStainedSlice entity and as the image is not annotated except perhaps for a scale bar it does not easily fit within AnnotatedSlice entity.  

To address this issue, I included the low magnification image as a file generated from LabeledCell entity - as it contains the related anatomical coordinates information - though this may not be the best solution, i.e. in yaml format:

```
LabeledCell:
  name:
  brainLocation:
  coordinatesinBrainAtlas:
    rostrocaudal:
    lateral:
    dorsal:
  locationInSlice:
  putativeMType:
  generated:                      <---- low-mag filename
  comment: 

```
