### ISSUE TITLE
YAML Templates for In Vitro Slice Neuron Morphology Reconstruction schema

### ISSUE THREAD

**Issue by jmbudd** [INCF/neuroshapes#361]
In the process of applying Neuroshapes In Vitro Slice Neuron Morphology Reconstruction schema to the curation of combined anatomical and electrophysiolgical slice data from mouse hippocampus, I encountered a number of issues. Since these issues may well arise during the curation of similar datasets for other labs, I thought it might be useful to share them here. I have created a separate ticket for each issue. (This introductory paragraph is repeated in each.)

Unless a experimental data collection process is fully automated, at least some metadata are supplied by manual user input. To minimize input/typing errors, I think it would help to make available blank template forms matching the Neuroshapes schema. The template forms should be in a format to make data digestion easier into an integrated database. Based on my experience, the YAML format may be a good option here. YAML is human-readable and a superset of JSON but with minimal use of separators (e.g. avoids matching nested brackets issue of JSON). In addition, YAML's indented hierarchy representation has a more compact and user-friendly appearance for editing than JSON or XML alteratives. Excel spreadsheets don't cope as well with hierarchical data and are prone to drag-and-fill error, e.g. "Protocol1" drag-and-copy can generate "Protocol2". Plain text templates may also help increase the adoption of Neuroshapes for the consistent management of experimental data. 

Below is an example YAML template for the Slice schema for a single neuron (as amended - see associated tickets)

```
Subject:
  id: 
  species: 
  strain: 
  sex: 
  age: 
  animal_weight: 
  date: 
  comment:

Slice:
  protocol:
  person:
  date:
  solution: 
  brainLocation:
  cuttingThickness:
  generated:
  hemisphere:
  slicingPlane:
  slicingAngle:
  comment:

PatchedSlice:
  protocol:
  person:
  date:
  name:
  brainLocation:
  bathSolution: 
  temperature:
  recordingType:
  intracellularSolution:
  generated:
  comment:

FixedStainedSlice:
  protocol:
  person:
  date:
  name:
  comment:

ImagedSlice:
  protocol:
  person:
  date:
  name:
  generated:
  comment:
    
LabeledCell:
  name:
  brainLocation:
  coordinatesinBrainAtlas:
    rostrocaudal:
    lateral:
    dorsal:
  locationInSlice:
  putativeMType:
  generated:
  comment: 

ReconstructedCell:
  protocol:
  person:
  date:
  name:
  mType:
  axonProjection:
  compressionCorrection:
  shrinkageCorrection:
  geometryCorrected: 
```
